Assignment 1 added
sharyu04/GoLangAssignments pull request #1
Opened 2024-01-22 10:39 UTC by sharyu04

1. Write a program to calculate the simple interest 
First-line has the comma-separated values of the Principal, rate and time (in years) respective
*constraints: Round simple interest float value to 2 decimal places
2. Write a program to calculate the area of the circle, First line has a value of the radius of the circle
constraint
1. Use const PI from the package math package
2. Use the Pow function from the math package
3. Round area float value to 2 decimal places

2024-01-22 17:04 UTC, Deepak1124 requested changes

2024-01-22 17:04 UTC, Deepak1124 commented on Assgn1/Q1.go
> +	principal := 1000
Please take input from user

2024-01-22 17:04 UTC, Deepak1124 commented on Assgn1/Q1.go
> +	Time := 3
Use proper functions(from main function) to call business logic

2024-01-22 17:04 UTC, Deepak1124 commented on Assgn1/Q1.go
> +	fmt.Println("Simple Interest = ", ans)
Use fmt.Print() instead, to do proper formatting

2024-01-22 17:04 UTC, Deepak1124 commented on Assgn1/Q2.go
> +	var radius float64
Please take input from user

2024-01-22 17:04 UTC, Deepak1124 commented on Assgn1/Q2.go
> +	area = math.Pi * math.Pow(radius, 2)
Use proper functions(from main function) to call business logic

2024-01-22 17:04 UTC, Deepak1124 commented on Assgn1/Q2.go
> +	fmt.Println("Area = ",ans)
Use fmt.Print() instead, to do proper formatting

2024-01-23 11:06 UTC, sharyu04 commented on Assgn1/Q1.go
> +	principal := 1000
The changes are done

2024-01-23 11:07 UTC, sharyu04 commented on Assgn1/Q1.go
> +	Time := 3
The changes are done

2024-01-23 11:07 UTC, sharyu04 commented on Assgn1/Q1.go
> +	fmt.Println("Simple Interest = ", ans)
Changes done

2024-01-23 11:09 UTC, sharyu04 commented on Assgn1/Q2.go
> +	var radius float64
Changes are done

2024-01-23 11:09 UTC, sharyu04 commented on Assgn1/Q2.go
> +	area = math.Pi * math.Pow(radius, 2)
Changes done

2024-01-23 11:09 UTC, sharyu04 commented on Assgn1/Q2.go
> +	fmt.Println("Area = ",ans)
Changes done

2024-01-23 11:54 UTC, merged